### ISSUE TITLE
excludePathPrefixes config option is missing in dist folder

### ISSUE THREAD

**Issue by flohil** [amorey/edge-csrf#10]
Hi!

I just installed version `1.0.3` of `edge-csrf` and it seems the `excludePathPrefixes` config option is missing in the packaged `dist` folder.

<img width="447" alt="image" src="https://github.com/amorey/edge-csrf/assets/6840090/216d2438-5949-4469-bac3-5337a0c253e4">

As a workaround, one can manually skip the invocation of `csrfProtect` in `middleware.ts`:

```
export async function middleware(req: NextRequest) {
  const res = NextResponse.next();

  if (!req.nextUrl.pathname.startsWith('/_next/')) {
    csrfProtect(req, res);
  }
```

**Comment by amorey** [comment]
Thanks for the heads up! Try v1.0.4:
https://www.npmjs.com/package/edge-csrf/v/1.0.4

**Comment by amorey** [comment]
@flohil Did v1.0.4 fix the issue?

**Comment by flohil** [comment]
Hey @amorey! Version 1.0.4 now includes the `excludePathPrefixes` config option in the dist folder.  Thank you for the fast fix!

**Comment by flohil** [comment]
Hey @amorey! Version 1.0.4 now includes the `excludePathPrefixes` config option in the dist folder.  Thank you for the fast fix!
