### ISSUE TITLE
CSRF on App not working

### ISSUE THREAD

**Issue by kjavier** [amorey/edge-csrf#12]
headers() only provides read-only request data and not from response data.

CSRF is attached to response headers.

Are you able to successfully get any csrf data from any server components in the app directory
just by using headers()?

**Comment by amorey** [comment]
Using headers() to retrieve the response header set by edge-csrf is working in the example here: https://github.com/amorey/edge-csrf/tree/main/example-ts-appdir

I just tried it with the latest version of Next.js (13.4.16) and it also worked.

Do you have an example of it not working with the app router?

**Comment by amorey** [comment]
Ok, thanks for the update. Happy to hear the issue wasn't with edge-csrf.
