### ISSUE TITLE
Next.js v14 Bump

### ISSUE THREAD

**Issue by Gbuomprisco** [amorey/edge-csrf#15]
Hi there, 

thanks for this package!

Opening this issue just to report Next.js v14 has been released and needs a bump :)

Thank you!

**Comment by amorey** [comment]
Thanks for the heads up! I tested the code against Next.js 14 and everything seems to be working. Here's a new version with v14 in the peer dependency list:
https://www.npmjs.com/package/edge-csrf/v/1.0.6-rc1

Let me know if everything is working and I can bump the edge-csrf version number. Here are some examples with Next.js 14:
https://github.com/amorey/edge-csrf/tree/next14/examples

**Comment by Gbuomprisco** [comment]
> Thanks for the heads up! I tested the code against Next.js 14 and everything seems to be working. Here's a new version with v14 in the peer dependency list: https://www.npmjs.com/package/edge-csrf/v/1.0.6-rc1
> 
> Let me know if everything is working and I can make a new stable release. Here are some examples with Next.js 14: https://github.com/amorey/edge-csrf/tree/next14/examples

Thank you so much for the quick release! Working all good here :)

**Comment by amorey** [comment]
Great! Bumped https://github.com/amorey/edge-csrf/releases/tag/v1.0.6
