### ISSUE TITLE
Sentry & CSRF

### ISSUE THREAD

**Issue by mosnicholas** [amorey/edge-csrf#19]
I’m using Sentry to monitor my FE application and edge-csrf to manage the CSRF security configurations. 

Sentry sets up a /monitoring endpoint to report metrics / monitoring events. We can obviously exclude this endpoint from our middleware / CSRF checks, but I’m curious if there’s a known way to wrap those Sentry API calls in similar edge-csrf logic to ensure all the app’s endpoints are protected properly.

**Comment by amorey** [comment]
I couldn't find a way to add CSRF protection to Sentry natively or a recommended way to integrate it with a custom CSRF solution but one way to do it with `edge-csrf` is to add the CSRF token as an HTTP header to Sentry events by providing a custom transport to the client config that wraps the native `fetch()` method (sentry.client.config.ts):

```typescript
import * as Sentry from "@sentry/nextjs";
import type { BaseTransportOptions } from '@sentry/types';

async function fetchWithCSRFHeader(input: RequestInfo | URL, init: RequestInit = {}): Promise<Response> {
  // ** must be implemented **
  const csrfToken = getCSRFToken();

  // add token to headers
  const headers = new Headers(init.headers);
  headers.append('X-CSRF-Token', csrfToken);

  // construct init object with the updated headers
  const modifiedInit = { ...init, headers };

  // call native fetch function with the original input and the modified init object
  return fetch(input, modifiedInit);
}

Sentry.init({
  dsn: "https://REPLACEME.ingest.sentry.io/REPLACEME",

  // Adjust this value in production, or use tracesSampler for greater control
  tracesSampleRate: 1,

  // Setting this option to true will print useful information to the console while you're setting up Sentry.
  debug: false,

  replaysOnErrorSampleRate: 1.0,

  // This sets the sample rate to be 10%. You may want this to be 100% while
  // in development and sample at a lower rate in production
  replaysSessionSampleRate: 0.1,

  // You can remove this option if you're not planning to use the Sentry Session Replay feature:
  integrations: [
    new Sentry.Replay({
      // Additional Replay configuration goes in here, for example:
      maskAllText: true,
      blockAllMedia: true,
    }),
  ],

  transport: (options: BaseTransportOptions) => {
    return Sentry.makeFetchTransport(options, fetchWithCSRFHeader);
  }
});
```

Here's a more complete example that adds a `/csrf-token` endpoint to a Next app and uses that endpoint to fetch a CSRF token for the Sentry client to use at request-time. You can cache to token to improve performance or make it available in other ways if you'd prefer:
https://github.com/amorey/edge-csrf/tree/main/examples/next14-approuter-sentry
