### ISSUE TITLE
NPM package is missing dist fodler in v1.0.0 

### ISSUE THREAD

**Issue by AndriiTsok** [amorey/edge-csrf#3]
The installed package of v1.0.0 cannot resolve the reference because the dist folder was not published to NPM.

https://www.npmjs.com/package/edge-csrf/v/1.0.0?activeTab=explore

**Comment by amorey** [comment]
Yikes! I don't know how that happened. I just re-published to npm and it looks like the `dist/` directory is there now (v1.0.1):
https://www.npmjs.com/package/edge-csrf/v/1.0.1?activeTab=explore

Thanks for the bug report!

**Comment by AndriiTsok** [comment]
@amorey thank you for such a quick reply!
