### ISSUE TITLE
Next 13.3.x breaks edge-csrf

### ISSUE THREAD

**Issue by ff6347** [amorey/edge-csrf#8]
When using next 13.3.1 the token is not accessible in getServerSideProps from the response header. in 13.2.4 everything works fine.
See #7 for some context.

**Comment by ff6347** [comment]
The documentation on edge API Routes states that 
> Note: Using Edge Runtime with getServerSideProps does not give you access to the response object. If you need access to res, you should use the Node.js runtime by setting runtime: 'nodejs'.

https://nextjs.org/docs/api-routes/edge-api-routes#differences-between-api-routes

**Comment by amorey** [comment]
This appears to be an issue with the dev server in Next.js 13.3.X: https://github.com/vercel/next.js/issues/48083

I posted a comment there as well. Hopefully someone from the dev team will respond soon to give us an update on the issue.

**Comment by olawale-o** [comment]
Hi @amorey 
Great work with **edge-csrf** package.
I would like to know if you have a documentation on how to use this package with **Next.js 13.2** using **app** directory. I went through the README and I noticed the doc was written for **pages** directory

**Comment by amorey** [comment]
@olawale-o Here's an example with the app/ directory (using Next.js 13.4):
https://github.com/amorey/edge-csrf/tree/main/example-ts-appdir

I don't have much experience using the app/ directory so let me know if you have any suggestions on how to improve the example.

**Comment by olawale-o** [comment]
H @amorey 
It worked fine with (**Next.js 13.4**) however not with (**Next.js 13.2**). I had to upgrade my project for it to work. I have added an example to the **example-ts-appdir** on how I used it for my use case. Kindly take a look and review the [PR](https://github.com/amorey/edge-csrf/pull/9)

**Comment by amorey** [comment]
Yes, that's expected. `example-ts-appdir` specifies Next.js 13.4 in its package.json. It appears that the bug referred to in this issue is present in the pages/ directory, not the app/ directory. Thanks for your PR, I'll take a look and respond there.

**Comment by andrebask** [comment]
Hi, I've also experienced this issue. As a workaround, I've been able to get the header like this
```typescript
const csrfToken = res.req.headers["x-csrf-token"] as string;
```
instead of
```typescript
const csrfToken = res.getHeader('X-CSRF-Token');
```

**Comment by HFR1994** [comment]
This also works:

```
export async function getServerSideProps(context) {
    const csrfToken = context.req.headers['x-csrf-token'] || 'missing';
    return { props: { csrfToken } };
}
```

I don't know if It has to do with but I keep getting **Invalid CSRF Token** even when it does attach a CSRF token

**Comment by amorey** [comment]
FYI I just tried edge-csrf with Next.js 13.5.X and it works! I also tried with Next.js 14.0.X and it's also working so it appears the middleware issue in the dev environment was fixed. I added a note to the README to highlight this issue:
https://github.com/amorey/edge-csrf/tree/next14
